name: lapsrn-baseline
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10.14
  - pip=23.3.1
  - pytorch=2.2.1
  - torchvision=0.17.1
  - numpy=1.26.3
  - pip:
    - swanlab=0.3.13
    - -e .




